on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # tag:
  #   - '*'
env:
  ALPINE_IMAGE: alpine
  ALPINE_IMAGE_URL: ${DOCKERHUB_REGISTRY}/${ALPINE_IMAGE}
  ALPINE_IMAGE_VERSION: 3.18.3
  BUSYBOX_IMAGE: busybox
  BUSYBOX_IMAGE_URL: ${DOCKERHUB_REGISTRY}/${BUSYBOX_IMAGE}
  BUSYBOX_IMAGE_VERSION: 1.36.1-musl
  # CGO_ENABLED: 1
  CI: "true"
  # CI_DEBUG_TRACE: "true"
  COMMIT_AUTHOR: ${CI_COMMIT_AUTHOR}
  COMMIT_SHA: ${CI_COMMIT_SHA}
  COSIGN_PASSWORD: 00000000-0000-0000-0000-000000000000
  DIND_IMAGE: docker
  DIND_IMAGE_URL: ${DOCKERHUB_REGISTRY}/${DIND_IMAGE}
  DIND_IMAGE_VERSION: 24.0.6-dind-alpine3.18
  DISTROLESS_IMAGE: distroless/static-debian11
  DISTROLESS_IMAGE_DIGEST: sha256:92d40eea0b5307a94f2ebee3e94095e704015fb41e35fc1fcbd1d151cc282222
  DISTROLESS_IMAGE_URL: ${GITHUB_REGISTRY}/${DISTROLESS_IMAGE}
  DISTROLESS_IMAGE_VERSION: nonroot
  DOCKERHUB_REGISTRY: docker.io
  DOCKER_CERT_PATH: ${DOCKER_TLS_CERTDIR}/client
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_TLS_VERIFY: 1
  GITHUB_REGISTRY: gcr.io
  GITOPS_PROJECT_ID: 147
  GITOPS_PROJECT_URL: github.com/arium-gg/gitops-next.git
  GITLAB_API_URL: ${CI_API_V4_URL}
  GITLAB_SERVER_URL: ${CI_SERVER_URL}
  GITLAB_TOKEN: ${CI_JOB_TOKEN}
  GIT_DEPTH: 1
  GIT_STRATEGY: fetch
  # GIT_SUBMODULE_DEPTH: 1
  # GIT_SUBMODULE_STRATEGY: recursive
  # GOGC: 50
  GOLANG_IMAGE: golang
  GOLANG_IMAGE_URL: ${DOCKERHUB_REGISTRY}/${GOLANG_IMAGE}
  GOLANG_IMAGE_VERSION: 1.21.1-alpine3.18
  GORELEASER_IMAGE: goreleaser/goreleaser
  GORELEASER_IMAGE_URL: ${DOCKERHUB_REGISTRY}/${GORELEASER_IMAGE}
  GORELEASER_IMAGE_VERSION: v1.21.2
  GRPC_HEALTH_PROBE_VERSION: v0.4.19
  # HUGO_ENV: production
  NODE_IMAGE: node
  NODE_IMAGE_URL: ${DOCKERHUB_REGISTRY}/${NODE_IMAGE}
  NODE_IMAGE_VERSION: 18.18.0-alpine3.18
  # OPENAPIV2_VERSION: ${CI_COMMIT_TAG}
  PRIVATE_REGISTRY: ghcr.io/arium-gg/preon
  PRIVATE_REGISTRY_LIBRARY: ${PRIVATE_REGISTRY}/library/
  PRIVATE_REGISTRY_TEMP: ${PRIVATE_REGISTRY}/temp/
  PROJECT_NAME: ${CI_PROJECT_NAME}
  PROJECT_URL: ${CI_PROJECT_URL}
  # REGISTRY: ${PRIVATE_REGISTRY_LIBRARY}
  SECRET_DETECTION_HISTORIC_SCAN: "true"
  SECURE_LOG_LEVEL: error

jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: run first step
        uses: actions/checkout@v4
      - name: run second step
        uses: actions/setup-go@v4
      - name: Install dependencies
        run: go mod download